name: Deploy Infrastructure (Task 1)

on:
  push:
    paths:
      - 'task1/**'
  workflow_dispatch:

env:
  DIGITALOCEAN_TOKEN: ${{ secrets.DO_PAT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
  SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
  SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' 
        run: terraform apply -auto-approve tfplan